url: "" # the base hostname & protocol for your site, e.g. https://example.com
base_path: "/"

permalink: pretty
template_engine: liquid
# ensure you use the `relative_url` helper for all links and assets in your HTML.
# If you're using esbuild for frontend assets, edit `esbuild.config.js` to
# update `publicPath`.

timezone: America/New_York
pagination:
  enabled: true

